### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by grahamrenney** [dbelyaev/action-checkstyle#20]
Hi.

The Java version for this action's docker container is v8. Checkstyle 10.4 requires >= 11

So if the checkstyle_version config item is set as follows:

checkstyle_version: 10.4

This exception is thrown:

Error: Exception in thread "main" java.lang.UnsupportedClassVersionError: com/puppycrawl/tools/checkstyle/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
reviewdog: parse error: EOF

**Comment by oldy-22** [comment]
Java Version for .class Files esp. **Compiler Compliance Level** you set with Java Compiler Options in your prefered IDE. 

For Eclipse this is: 
Window - Preferences - JAVA - Compiler - JDK Compliance - Compiler Compliance Level

**Comment by dbelyaev** [comment]
@grahamrenney
Excuse me for the late response: I did upgrade JDK used in a container to the OpenJDK v17 LTS. 
Please, use this release: https://github.com/dbelyaev/action-checkstyle/releases/tag/v0.7.0
